Implementa tradução em PT-BR do README.md
luis-saes/generic-dashboard pull request #19
Opened 2022-09-01 23:00 UTC by paulorsv01

Description: This PR contains a translation in Brazilian Portuguese for the project `README.md` file.

Fixes #12

2022-09-04 16:31 UTC, luis-saes requested changes
EN: Awesome job, amazing translation. There's only one small tweak requested! Keep up the good work!
PT: Excelente trabalho, tradução incrível. Há uma unica modificação requisitada. Continue com o bom trabalho!

2022-09-04 16:31 UTC, luis-saes commented on README-pt-BR.md
> +1. Escolha uma tarefa do repositório e deixe um comentário expressando interesse em resolvê-la.
EN: Change from "tarefa" to "issue".
PT: Altere de "tarefa" para "issue".
```suggestion
1. Escolha uma issue do repositório e deixe um comentário expressando interesse em resolvê-la.
```

2022-09-04 16:31 UTC, luis-saes commented on README-pt-BR.md
> +3. Faça um fork do repositório, crie uma nova branch e desenvolva o trabalho solicitado na tarefa, utilizando o arquivo correto para efetuar as modificações, como especificado na tarefa escolhida.
EN: Change from "tarefa" to "issue".
PT: Altere de "tarefa" para "issue".
```suggestion
3. Faça um fork do repositório, crie uma nova branch e desenvolva o trabalho solicitado na issue, utilizando o arquivo correto para efetuar as modificações, como especificado na issue escolhida.
```

2022-09-04 16:31 UTC, luis-saes commented on README-pt-BR.md
> +Fixes #<NÚMERO DA TAREFA QUE FOI RESOLVIDA>
EN: Change from "tarefa" to "issue".
PT: Altere de "tarefa" para "issue".
```suggestion
Fixes #<NÚMERO DA ISSUE QUE FOI RESOLVIDA>
```

2022-09-04 17:01 UTC, paulorsv01 commented
> EN: Awesome job, amazing translation. There's only one small tweak requested! Keep up the good work! PT: Excelente trabalho, tradução incrível. Há uma unica modificação requisitada. Continue com o bom trabalho!

Done!

2022-09-05 13:08 UTC, luis-saes approved these changes

2022-09-05 13:10 UTC, merged

2022-09-05 13:11 UTC, luis-saes commented
Thank you and congrats!! Awesome job!! ✨✨